# Generated by Django 3.0.7 on 2020-09-30 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='checkout.Order'),
        ),
    ]
