# Generated by Django 3.0.7 on 2020-06-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_item_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_total',
            new_name='total',
        ),
    ]
