# Generated by Django 3.0.7 on 2020-06-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200612_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
