# Generated by Django 3.0.7 on 2020-06-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200619_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted',
            new_name='discount',
        ),
    ]
